# coding: utf-8
from basedevice import BaseDevice
import basecommand 
import json
import re
from utils import mac_string_2_array, ip_string_2_array,getuptime
import time
class UnifiAPLite(BaseDevice):
    def __init__(self,configfile):
        BaseDevice.__init__(self,'U7LT','UAP-AC-Lite',configfile)
                
    def cfgversion(self):
        if self.config.has_section('mgmt_cfg') and self.config.has_option('mgmt_cfg','cfgversion'):
            print(self.config.get('mgmt_cfg', 'cfgversion')) 
            return self.config.get('mgmt_cfg', 'cfgversion')     
        else:
            return "?"    
    def version(self):
        return self.config.get('mgmt_cfg', 'cfgversion')       
    def getCurrentMessageType(self):
        if self.config.has_section('gateway') and not self.config.getboolean('gateway', 'is_adopted') and self.config.get('gateway', 'key')=="" :
            return -1     
        if self.config.has_section('gateway') and not self.config.getboolean('gateway', 'is_adopted') and not self.config.get('gateway', 'key')=="" : #discover
            return 1     
        if self.config.has_section('gateway') and self.config.getboolean('gateway', 'is_adopted') : #info
            return 2     
    def getInformUrl(self):
        return self.config.get('gateway', 'url')
    def getInformIp(self):
        return "192.168.106.172"                      
    def getHostname(self):
        return "UBNT"      
    def getKey(self):
        return self.config.get('gateway', 'key')

    def _save_config(self):
        with open(self.configfile, 'w') as config_file:
            self.config.write(config_file)
    
    def parseResponse(self,data):
        result = json.loads(data)
        if result['_type'] == 'setparam':
            for key, value in result.items():
                if key not in ['_type', 'server_time_in_utc', 'mgmt_cfg','system_cfg']:
                    self.config.set('gateway', key, value)
                elif key not in ['_type', 'server_time_in_utc']:
                    if not self.config.has_section(key):
                        self.config.add_section(key)
                    lines = re.split('\n',value) 
                    for line in lines:
                        if not line =='':
                            data = re.split('=',line) 
                            self.config.set(key, data[0], data[1]) 
            wasAdopted = self.config.getboolean('gateway', 'is_adopted')
            self.config.set('gateway', 'is_adopted', 'yes')
            self._save_config()
            self.config.read(self.configfile)
            self.nextCommand = basecommand.BaseCommand(basecommand.CMD_NOTIFY,self.createNotify())
            self.delayStart-=self.interval

    def send_discover(self):
        base = self.createDiscover()
        self.parseResponse(self._send_inform(base,True))
    def send_inform(self):
        base = self.createInform()
        self.parseResponse(self._send_inform(base,False))
    def send_notify(self,wasAdopted):
        self.parseResponse(self._send_inform(self.createNotify(),False))
    def createNotify(self):
        data ={
            "architecture": "mips",
            "board_rev": 33,
            "bootid": 1,
            "bootrom_version": "unifi-enlarge-buf.-1-g63fe9b5d-dirty",
            "cfgversion": "773e98c81e267e99",
            "default": False,
            "discovery_response": True,
            "dualboot": True,
            "hash_id": self.cfgversion(),
            "hostname": "UBNT",
            "inform_as_notif": True,
            "inform_ip": self.getInformIp(),
            "inform_url": self.getInformUrl(),
            "ip": self.ip,
            "isolated": False,
            "kernel_version": "4.4.153",
            "last_error": "Unable to resolve (http://unifi:8080/inform)",
            "locating": False,
            "mac": self.mac,
            "manufacturer_id": 4,
            "model": "U7LT",
            "model_display": "UAP-AC-Lite",
            "netmask": "255.255.255.0",
            "notif_payload": "",
            "notif_reason": "setparam",
            "required_version": "3.4.1",
            "selfrun_beacon": True,
            "serial": self.mac.replace(':', ''),
            "state": 0,
            "time": int(time.time()),
            "time_ms": 2,
            "uptime": getuptime(),
            "version": "4.0.80.10875"
            }
        
        return data
    def createDiscover(self):
        data={
        "antenna_table": [
            {
            "default": True,
            "id": 4,
            "name": "Combined",
            "wifi0_gain": 3,
            "wifi1_gain": 3
            }
        ],
        "architecture": "mips",
        "board_rev": 33,
        "bootid": 1,
        "bootrom_version": "unifi-enlarge-buf.-1-g63fe9b5d-dirty",
        "cfgversion": "?",
        "country_code": 0,
        "countrycode_table": [],
        "default": True,
        "discovery_response": True,
        "dualboot": True,
        "ever_crash": False,
        "fingerprint": "7c:82:af:cf:3d:fd:ec:41:f7:41:1b:34:26:9d:fd:23:b2:8d:22:2a",
        "fw_caps": 25099327,
        "gateway_ip": "192.168.1.1",
        "gateway_mac": "90:94:e4:82:a0:e7",
        "guest_token": "87ABB2343693204D10D5AC2755E6F8EC",
        "has_eth1": False,
        "has_speaker": False,
        "hash_id": "d3accea4a93710a7",
        "hostname": "UBNT",
        "hw_caps": 0,
        "if_table": [
            {
            "full_duplex": True,
            "ip": "0.0.0.0",
            "mac": "78:8a:20:dc:43:89",
            "name": "eth0",
            "netmask": "0.0.0.0",
            "num_port": 1,
            "rx_bytes": 52681,
            "rx_dropped": 0,
            "rx_errors": 0,
            "rx_multicast": 0,
            "rx_packets": 188,
            "speed": 1000,
            "tx_bytes": 7972,
            "tx_dropped": 0,
            "tx_errors": 0,
            "tx_packets": 67,
            "up": True
            }
        ],
        "inform_ip": self.getInformIp(),
        "inform_url": self.getInformUrl(),
        "ip": self.ip,
        "isolated": False,
        "kernel_version": "4.4.153", 
        "last_error": "Unable to resolve (http://unifi:8080/inform)",
        "locating": False,
        "mac": self.mac,
        "manufacturer_id": 4,
        "model": "U7LT",
        "model_display": "UAP-AC-Lite",
        "netmask": "255.255.255.0",
        "qrid": "7TKgqK",
        "radio_table": [
            {
            "athstats": {
                "ast_ath_reset": 0,
                "ast_be_xmit": 133,
                "ast_cst": 0,
                "ast_deadqueue_reset": 0,
                "ast_fullqueue_stop": 0,
                "ast_txto": 0,
                "cu_self_rx": 27,
                "cu_self_tx": 2,
                "cu_total": 30,
                "n_rx_aggr": 0,
                "n_rx_pkts": 1363,
                "n_tx_bawadv": 0,
                "n_tx_bawretries": 0,
                "n_tx_pkts": 0,
                "n_tx_queue": 0,
                "n_tx_retries": 0,
                "n_tx_xretries": 0,
                "n_txaggr_compgood": 0,
                "n_txaggr_compretries": 0,
                "n_txaggr_compxretry": 0,
                "n_txaggr_prepends": 0,
                "name": "wifi0",
                "noise_floor": -95,
                "satisfaction": -1,
                "satisfaction_now": -1
            },
            "builtin_ant_gain": 3,
            "builtin_antenna": True,
            "ieee_modes": 10,
            "max_txpower": 20,
            "min_txpower": 4,
            "name": "wifi0",
            "nss": 2,
            "radio": "ng",
            "radio_caps": 16404,
            "scan_table": [
                {
                "age": 9,
                "band": "ng",
                "bssid": "68:ff:7b:47:0f:76",
                "bw": 20,
                "center_freq": 2432,
                "channel": 5,
                "essid": "LaunchOptions",
                "freq": 2432,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 0,
                "rssi_age": 42949433,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -96
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "f0:9f:c2:27:eb:e4",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 12,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "F09FC226EBE4",
                "signal": -84
                },
                {
                "age": 8,
                "band": "ng",
                "bssid": "f4:60:e2:d7:a5:de",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "AndroidAP_8705",
                "freq": 2437,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 5,
                "rssi_age": 8,
                "security": "WPA2 (AES/CCMP)",
                "signal": -91
                },
                {
                "age": 8,
                "band": "ng",
                "bssid": "fc:ec:da:a1:64:9a",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "fistashki",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 6,
                "rssi_age": 8,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "serialno": "FCECDAA0649A",
                "signal": -90
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "ce:2d:e0:e7:d8:70",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "GKeyLab",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 16,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -80
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "9c:3d:cf:4a:05:7c",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_1576852459",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 9,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -87
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "cc:40:d0:85:0d:f4",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "NTGR_VMB_1576851146",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 14,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -82
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "76:4d:28:1e:6a:7a",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "GKeyLab",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 20,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -76
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "74:4d:28:1e:6a:79",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 18,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -78
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "cc:2d:e0:e7:d8:70",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 17,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -79
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "92:5b:ad:94:b8:27",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "DESKTOP-7KQ17SQ 9158",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 43,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -53
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "92:5b:ad:91:be:c1",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "DESKTOP-7KQ17SQ 1823",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 37,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -59
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "78:d2:94:09:d9:96",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_8960550083",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 14,
                "rssi_age": 13,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -82
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "a4:11:62:1b:0e:e6",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_1325437673",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 13,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -83
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "a4:11:62:0e:ce:c1",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_1576846250",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 19,
                "rssi_age": 13,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -77
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "a4:11:62:0e:ce:2b",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_9395717404",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 17,
                "rssi_age": 13,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -79
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "a4:11:62:0e:ce:d3",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_1582040096",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 14,
                "rssi_age": 13,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -82
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "86:2a:a8:2d:98:30",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "wiubi",
                "freq": 2462,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "BZ2",
                "model_display": "UAP",
                "noise": -96,
                "rssi": 21,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "802AA82C9830",
                "signal": -75
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "a4:11:62:0e:ce:e2",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_3805595378",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 15,
                "rssi_age": 13,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -81
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "10:7b:ef:5c:27:9c",
                "bw": 40,
                "center_freq": 2452,
                "channel": 11,
                "essid": "Keenetic-Lumin",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 46,
                "rssi_age": 13,
                "security": "WPA2 (AES/CCMP)",
                "signal": -50
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "a4:11:62:0e:ce:67",
                "bw": 20,
                "center_freq": 2462,
                "channel": 11,
                "essid": "ARLO_VMB_9295149558",
                "freq": 2462,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 17,
                "rssi_age": 13,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -79
                },
                {
                "age": 13,
                "band": "ng",
                "bssid": "60:31:97:3c:42:08",
                "bw": 40,
                "center_freq": 2447,
                "channel": 10,
                "essid": "sen-wifi",
                "freq": 2457,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 41,
                "rssi_age": 14,
                "security": "WPA2 (AES/CCMP)",
                "signal": -55
                },
                {
                "age": 14,
                "band": "ng",
                "bssid": "74:4d:28:d6:4d:15",
                "bw": 40,
                "center_freq": 2457,
                "channel": 8,
                "essid": "conference7th",
                "freq": 2447,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 12,
                "rssi_age": 14,
                "security": "WPA2 (AES/CCMP)",
                "signal": -84
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "a6:83:c2:37:41:2f",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": True,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": True,
                "model": "U7LT",
                "model_display": "UAP-AC-Lite",
                "noise": -96,
                "rssi": 16,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C236412F",
                "signal": -80
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "64:d1:54:89:46:39",
                "bw": 40,
                "center_freq": 2432,
                "channel": 7,
                "essid": "BelTourist",
                "freq": 2442,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 36,
                "rssi_age": 14,
                "security": "WPA2 (AES/CCMP)",
                "signal": -60
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "d2:c0:bf:a4:c6:74",
                "bw": 40,
                "center_freq": 2427,
                "channel": 6,
                "essid": "Mirascreen BFA4C674",
                "freq": 2437,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 14,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "signal": -82
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "c4:71:54:b6:8a:f6",
                "bw": 20,
                "center_freq": 2447,
                "channel": 8,
                "essid": "Office609",
                "freq": 2447,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 25,
                "rssi_age": 14,
                "security": "WPA2 (AES/CCMP)",
                "signal": -71
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "96:83:c2:37:41:2f",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "Digiteum.Test",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7LT",
                "model_display": "UAP-AC-Lite",
                "noise": -96,
                "rssi": 16,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C236412F",
                "signal": -80
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "f2:9f:c2:27:eb:e4",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "POIGuest",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 12,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "F09FC226EBE4",
                "signal": -84
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "b8:27:eb:85:9e:b4",
                "bw": 20,
                "center_freq": 2442,
                "channel": 7,
                "essid": "RaspCO2",
                "freq": 2442,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 34,
                "rssi_age": 14,
                "security": "WPA2 (AES/CCMP)",
                "signal": -62
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "74:83:c2:37:41:2f",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "Digiteum",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7LT",
                "model_display": "UAP-AC-Lite",
                "noise": -96,
                "rssi": 16,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C236412F",
                "signal": -80
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "86:83:c2:37:41:2f",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "Digiteum_IoT",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7LT",
                "model_display": "UAP-AC-Lite",
                "noise": -96,
                "rssi": 17,
                "rssi_age": 0,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C236412F",
                "signal": -79
                },
                {
                "age": 0,
                "band": "ng",
                "bssid": "76:83:c2:37:41:2f",
                "bw": 20,
                "center_freq": 2437,
                "channel": 6,
                "essid": "Digiteum.Guest",
                "freq": 2437,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7LT",
                "model_display": "UAP-AC-Lite",
                "noise": -96,
                "rssi": 17,
                "rssi_age": 0,
                "security": "Open",
                "serialno": "7483C236412F",
                "signal": -79
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "14:cc:20:d3:3f:c6",
                "bw": 40,
                "center_freq": 2422,
                "channel": 1,
                "essid": "IM-Action",
                "freq": 2412,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 0,
                "rssi_age": 42949433,
                "security": "WPA2 (AES/CCMP)",
                "signal": -96
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "68:cc:6e:cf:10:3c",
                "bw": 20,
                "center_freq": 2417,
                "channel": 2,
                "essid": "HUAWEI-xsSE",
                "freq": 2417,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 9,
                "rssi_age": 15,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -87
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "76:83:c2:2d:88:a5",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "Digiteum.Guest",
                "freq": 2412,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 32,
                "rssi_age": 15,
                "security": "Open",
                "serialno": "7483C22C88A5",
                "signal": -64
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "a6:83:c2:2d:88:a5",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "",
                "freq": 2412,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": True,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": True,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 32,
                "rssi_age": 15,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C22C88A5",
                "signal": -64
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "10:9a:dd:89:4f:a9",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "iDigiteum",
                "freq": 2412,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 29,
                "rssi_age": 15,
                "security": "WPA2 (AES/CCMP)",
                "signal": -67
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "86:83:c2:2d:88:a5",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "Digiteum_IoT",
                "freq": 2412,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 32,
                "rssi_age": 15,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C22C88A5",
                "signal": -64
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "a0:a3:3b:a6:3e:38",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "HUAWEI-yX8U",
                "freq": 2412,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 11,
                "rssi_age": 15,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -85
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "84:20:96:2d:9b:0f",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "test",
                "freq": 2412,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 32,
                "rssi_age": 15,
                "security": "Open",
                "signal": -64
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "74:83:c2:2d:88:a5",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "Digiteum",
                "freq": 2412,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 33,
                "rssi_age": 16,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C22C88A5",
                "signal": -63
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "f8:1a:67:32:19:00",
                "bw": 40,
                "center_freq": 2422,
                "channel": 1,
                "essid": "ATLANT611",
                "freq": 2412,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 31,
                "rssi_age": 15,
                "security": "WPA/WPA2 (TKIP/AES/CCMP)",
                "signal": -65
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "38:a2:8c:6f:b7:1c",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "test",
                "freq": 2412,
                "is_adhoc": False,
                "is_ubnt": False,
                "noise": -96,
                "rssi": 35,
                "rssi_age": 15,
                "security": "Open",
                "signal": -61
                },
                {
                "age": 15,
                "band": "ng",
                "bssid": "96:83:c2:2d:88:a5",
                "bw": 20,
                "center_freq": 2412,
                "channel": 1,
                "essid": "Digiteum.Test",
                "freq": 2412,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": False,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": False,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 33,
                "rssi_age": 16,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C22C88A5",
                "signal": -63
                }
            ]
            },
            {
            "athstats": {
                "ast_ath_reset": 4,
                "ast_be_xmit": 0,
                "ast_cst": 0,
                "ast_deadqueue_reset": 0,
                "ast_fullqueue_stop": 0,
                "ast_txto": 0,
                "cu_self_rx": 0,
                "cu_self_tx": 0,
                "cu_total": 0,
                "n_rx_aggr": 0,
                "n_rx_pkts": 156,
                "n_tx_bawadv": 0,
                "n_tx_bawretries": 0,
                "n_tx_pkts": 1080,
                "n_tx_queue": 0,
                "n_tx_retries": 1,
                "n_tx_xretries": 0,
                "n_txaggr_compgood": 0,
                "n_txaggr_compretries": 0,
                "n_txaggr_compxretry": 0,
                "n_txaggr_prepends": 0,
                "name": "wifi1",
                "noise_floor": -95,
                "satisfaction": -1,
                "satisfaction_now": -1
            },
            "builtin_ant_gain": 3,
            "builtin_antenna": True,
            "has_dfs": True,
            "has_fccdfs": True,
            "ieee_modes": 21,
            "is_11ac": True,
            "max_txpower": 20,
            "min_txpower": 4,
            "name": "wifi1",
            "nss": 2,
            "radio": "na",
            "radio_caps": 50479124,
            "scan_table": [
                {
                "age": 18,
                "band": "na",
                "bssid": "a6:83:c2:38:41:2f",
                "bw": 80,
                "center_freq": 5210,
                "channel": 44,
                "essid": "vwire-582287dd54033968",
                "freq": 5220,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": True,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": True,
                "model": "U7LT",
                "model_display": "UAP-AC-Lite",
                "noise": -96,
                "rssi": 13,
                "rssi_age": 18,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C236412F",
                "signal": -83
                },
                {
                "age": 18,
                "band": "na",
                "bssid": "a6:83:c2:2e:88:a5",
                "bw": 80,
                "center_freq": 5210,
                "channel": 44,
                "essid": "",
                "freq": 5220,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": True,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": True,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 24,
                "rssi_age": 18,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C22C88A5",
                "signal": -72
                },
                {
                "age": 18,
                "band": "na",
                "bssid": "a6:83:c2:2e:88:a5",
                "bw": 80,
                "center_freq": 5210,
                "channel": 44,
                "essid": "vwire-582287dd54033968",
                "freq": 5220,
                "fw_version": "",
                "is_adhoc": False,
                "is_default": False,
                "is_isolated": False,
                "is_locating": False,
                "is_meshv3": True,
                "is_ubnt": True,
                "is_unifi": True,
                "is_vport": False,
                "is_vwire": True,
                "model": "U7PG2",
                "model_display": "UAP-AC-Pro-Gen2",
                "noise": -96,
                "rssi": 24,
                "rssi_age": 18,
                "security": "WPA2 (AES/CCMP)",
                "serialno": "7483C22C88A5",
                "signal": -72
                }
            ]
            }
        ],
        "required_version": "3.4.1",
        "satisfaction": -1,
        "satisfaction_now": -1,
        "scan_radio_table": [],
        "selfrun_beacon": True,
        "serial": self.mac.replace(':', ''),
        "spectrum_scanning": False,
        "ssh_session_table": [],
        "state": 1,
        "stream_token": "",
        "sys_error_caps": 0,
        "sys_stats": {
            "loadavg_1": "0.88",
            "loadavg_15": "0.09",
            "loadavg_5": "0.27",
            "mem_buffer": 0,
            "mem_total": 128622592,
            "mem_used": 59133952
        },
        "system-stats": {
            "cpu": "0.0",
            "mem": "24.2",
            "uptime": getuptime()
        },
        "time": int(time.time()),
        "time_ms": 25,
        "tm_ready": True,
        "uplink": "eth0",
        "uptime": getuptime(),
        "vap_table": [
            {
            "anomalies_bar_chart": {
                "high_dns_latency": 0,
                "high_tcp_latency": 0,
                "high_tcp_packet_loss": 0,
                "high_wifi_latency": 0,
                "high_wifi_retries": 0,
                "low_phy_rate": 0,
                "poor_stream_eff": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "weak_signal": 0
            },
            "anomalies_bar_chart_now": {
                "high_dns_latency": 0,
                "high_tcp_latency": 0,
                "high_tcp_packet_loss": 0,
                "high_wifi_latency": 0,
                "high_wifi_retries": 0,
                "low_phy_rate": 0,
                "poor_stream_eff": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "weak_signal": 0
            },
            "avg_client_signal": 0,
            "bssid": "ff:ff:ff:ff:ff:ff",
            "ccq": 0,
            "channel": 36,
            "dns_avg_latency": -1,
            "essid": "",
            "id": "user",
            "mac_filter_rejections": 0,
            "name": "ath1",
            "num_satisfaction_sta": 0,
            "num_sta": 0,
            "radio": "na",
            "radio_name": "wifi1",
            "reasons_bar_chart": {
                "phy_rate": 0,
                "signal": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_latency": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "stream_eff": 0,
                "tcp_latency": 0,
                "tcp_packet_loss": 0,
                "wifi_latency": 0,
                "wifi_retries": 0
            },
            "reasons_bar_chart_now": {
                "phy_rate": 0,
                "signal": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_latency": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "stream_eff": 0,
                "tcp_latency": 0,
                "tcp_packet_loss": 0,
                "wifi_latency": 0,
                "wifi_retries": 0
            },
            "rx_bytes": 0,
            "rx_crypts": 0,
            "rx_dropped": 0,
            "rx_errors": 0,
            "rx_frags": 0,
            "rx_nwids": 0,
            "rx_packets": 0,
            "rx_tcp_stats": {
                "goodbytes": 0,
                "lat_avg": 0,
                "lat_max": 0,
                "lat_min": 4294967295,
                "stalls": 0
            },
            "satisfaction": -1,
            "satisfaction_now": -1,
            "sta_table": [],
            "state": "INIT",
            "tx_bytes": 0,
            "tx_combined_retries": 0,
            "tx_data_mpdu_bytes": 0,
            "tx_dropped": 0,
            "tx_errors": 0,
            "tx_packets": 0,
            "tx_power": 31,
            "tx_retries": 0,
            "tx_rts_retries": 0,
            "tx_success": 0,
            "tx_tcp_stats": {
                "goodbytes": 0,
                "lat_avg": 0,
                "lat_max": 0,
                "lat_min": 4294967295,
                "stalls": 0
            },
            "tx_total": 0,
            "up": False,
            "usage": "uplink",
            "wifi_tx_attempts": 0,
            "wifi_tx_dropped": 0
            },
            {
            "anomalies_bar_chart": {
                "high_dns_latency": 0,
                "high_tcp_latency": 0,
                "high_tcp_packet_loss": 0,
                "high_wifi_latency": 0,
                "high_wifi_retries": 0,
                "low_phy_rate": 0,
                "poor_stream_eff": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "weak_signal": 0
            },
            "anomalies_bar_chart_now": {
                "high_dns_latency": 0,
                "high_tcp_latency": 0,
                "high_tcp_packet_loss": 0,
                "high_wifi_latency": 0,
                "high_wifi_retries": 0,
                "low_phy_rate": 0,
                "poor_stream_eff": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "weak_signal": 0
            },
            "avg_client_signal": 0,
            "bssid": "78:8a:20:dd:43:89",
            "ccq": 0,
            "channel": 6,
            "dns_avg_latency": -1,
            "essid": "788A20DC4389",
            "id": "user",
            "mac_filter_rejections": 0,
            "name": "ath0",
            "num_satisfaction_sta": 0,
            "num_sta": 0,
            "radio": "ng",
            "radio_name": "wifi0",
            "reasons_bar_chart": {
                "phy_rate": 0,
                "signal": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_latency": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "stream_eff": 0,
                "tcp_latency": 0,
                "tcp_packet_loss": 0,
                "wifi_latency": 0,
                "wifi_retries": 0
            },
            "reasons_bar_chart_now": {
                "phy_rate": 0,
                "signal": 0,
                "sleepy_client": 0,
                "sta_arp_timeout": 0,
                "sta_dns_latency": 0,
                "sta_dns_timeout": 0,
                "sta_ip_timeout": 0,
                "stream_eff": 0,
                "tcp_latency": 0,
                "tcp_packet_loss": 0,
                "wifi_latency": 0,
                "wifi_retries": 0
            },
            "rx_bytes": 0,
            "rx_crypts": 0,
            "rx_dropped": 0,
            "rx_errors": 0,
            "rx_frags": 0,
            "rx_nwids": 42,
            "rx_packets": 0,
            "rx_tcp_stats": {
                "goodbytes": 0,
                "lat_avg": 0,
                "lat_max": 0,
                "lat_min": 4294967295,
                "stalls": 0
            },
            "satisfaction": -1,
            "satisfaction_now": -1,
            "sta_table": [],
            "state": "RUN",
            "tx_bytes": 0,
            "tx_combined_retries": 0,
            "tx_data_mpdu_bytes": 0,
            "tx_dropped": 59,
            "tx_errors": 0,
            "tx_packets": 0,
            "tx_power": 20,
            "tx_retries": 0,
            "tx_rts_retries": 0,
            "tx_success": 0,
            "tx_tcp_stats": {
                "goodbytes": 0,
                "lat_avg": 0,
                "lat_max": 0,
                "lat_min": 4294967295,
                "stalls": 0
            },
            "tx_total": 0,
            "up": True,
            "usage": "user",
            "wifi_tx_attempts": 0,
            "wifi_tx_dropped": 0
            }
        ],
        "version": "4.0.80.10875",
        "wifi_caps": 573429
        }
        return data                
                    
